# Generated by Django 6.0.1 on 2026-02-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genus', models.CharField(max_length=80)),
                ('species', models.CharField(max_length=150)),
                ('seed_type', models.CharField(choices=[('HYB', 'Hybrid'), ('OP', 'Open-Pollinated'), ('HE', 'Heirloom')], default='HYB', max_length=3)),
                ('continent', models.CharField(max_length=20)),
                ('slug', models.SlugField(help_text='SEO-friendly URLs', max_length=500, null=True)),
            ],
        ),
    ]
